# Phiên bản cú pháp của Docker Compose
version: "3.9"

services:
  # --- 1. CÁC DỊCH VỤ NỀN TẢNG (INFRASTRUCTURE) ---

  # Dịch vụ Database dùng chung cho tất cả các microservice
  hospital-db:
    image: mysql:8.0
    container_name: hospital-db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      #MYSQL_DATABASE: hospital_db
      MYSQL_ROOT_PASSWORD: admin@123
    ports:
      - "8080:8080" # Ánh xạ cổng để bạn có thể kết nối từ máy thật (Navicat, DBeaver)
    volumes:
      - hospital-db-data:/var/lib/mysql # Lưu trữ dữ liệu database bền vững
      - ./db-init:/docker-entrypoint-initdb.d

  # Dịch vụ Message Queue (RabbitMQ)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # Cổng cho các service kết nối
      - "15672:15672" # Cổng cho giao diện quản lý web (http://localhost:15672)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  # --- 2. CÁC DỊCH VỤ BACKEND (MICROSERVICES) ---

  auth-service:
    build: ./auth-service # Đường dẫn đến thư mục chứa Dockerfile
    container_name: auth-service
    ports:
      - "3000:3000" # Ánh xạ cổng <máy_host>:<container>
    env_file:
      - ./auth-service/.env # Nạp biến môi trường từ file .env
    depends_on: # Khởi chạy sau khi các dịch vụ nền tảng sẵn sàng
      - hospital-db
      - rabbitmq
    restart: unless-stopped
    command: npm run dev # Chạy bằng nodemon để hot-reload
    volumes: # Đồng bộ code để hot-reload
      - ./auth-service:/app
      - /app/node_modules

  patient-service:
    build: ./patient-service
    container_name: patient-service
    ports:
      - "3001:3001"
    env_file:
      - ./patient-service/.env
    depends_on:
      - hospital-db
      - rabbitmq
    restart: unless-stopped
    command: npm run dev
    volumes:
      - ./patient-service:/app
      - /app/node_modules

  appointment-service:
    build: ./appointment-service
    container_name: appointment-service
    ports:
      - "3002:3002"
    env_file:
      - ./appointment-service/.env
    depends_on:
      - hospital-db
      - rabbitmq
    restart: unless-stopped
    command: npm run dev
    volumes:
      - ./appointment-service:/app
      - /app/node_modules

  prescription-service:
    build: ./prescription-service
    container_name: prescription-service
    ports:
      - "3003:3003"
    env_file:
      - ./prescription-service/.env
    depends_on:
      - hospital-db
      - rabbitmq
    restart: unless-stopped
    command: npm run dev
    volumes:
      - ./prescription-service:/app
      - /app/node_modules

  # notification-service:
  #   build: ./notification-service
  #   container_name: notification-service
  #   ports:
  #     - "3004:3004"
  #   env_file:
  #     - ./notification-service/.env
  #   depends_on:
  #     - hospital-db
  #     - rabbitmq
  #   restart: unless-stopped
  #   command: npm run dev
  #   volumes:
  #     - ./notification-service:/app
  #     - /app/node_modules

  # report-service:
  #   build: ./report-service
  #   container_name: report-service
  #   ports:
  #     - "3005:3005"
  #   env_file:
  #     - ./report-service/.env
  #   depends_on:
  #     - hospital-db
  #     - rabbitmq
  #   restart: unless-stopped
  #   command: npm run dev
  #   volumes:
  #     - ./report-service:/app
  #     - /app/node_modules

# --- 3. KHAI BÁO CÁC TÀI NGUYÊN DÙNG CHUNG ---

# Khai báo volume để Docker quản lý, đảm bảo dữ liệu không bị mất
volumes:
  hospital-db-data: